# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25e950df18e902860ce0de6021fcdecf341cf1cd16c695bfc3f8f2290f1486ea1f383fc4e0b0473cf9b6fbf348c270a81d7ea139d991499dc18bc7090cd8ecf7

test:
  secret_key_base: d5724adc8d11c19222eb06e0c23af5f4ef3558d52066e3b2e61eb90e87164fc6db552eece3db77bf8fadf1ce2c66267e1f97b9b58731e4bac75caa756d88e8f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
